name: CI/CD DEV Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install fastapi uvicorn flake8 pytest httpx

      - name: Lint
        run: 
          flake8 .

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q fastapiproj_tests.py 

  docker_image:
    runs-on: ubuntu-latest    
    needs: test

    steps:
        - name: Log in to GitHub Container Registry
          run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
        - name: Build Docker image
          run: docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/my-fast-api-devops:latest .
  
        - name: Push Docker image
          run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/my-fast-api-devops:latest