name: CI/CD Prod Pipeline

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum update
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -aG docker ec2-user || true
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            sudo docker pull ghcr.io/${{ secrets.DOCKER_USERNAME }}/my-fast-api-devops:latest
            sudo docker stop my-fast-api-container || true
            sudo docker rm my-fast-api-container || true
            sudo docker run -d --name my-fast-api-container -p 8001:8000 ${{ secrets.DOCKER_USERNAME }}/my-fast-api-devops:latest